import { Builder, withChildren } from '@builder.io/react';
import ProForm, {ProFormDatePicker, ProFormDateRangePicker, ProFormDateTimePicker, ProFormDateTimeRangePicker, ProFormText, ProFormTextArea, ProFormTimePicker} from '@ant-design/pro-form';
import ProTable from '@ant-design/pro-table';
import { configProForm } from './components/ProForm.config';
import { configProFormText } from './components/ProFormText.config';
import { configProTable } from './components/ProTable.config';
import { configProFormDatePicker } from './components/ProFormDatePicker.config';
import { configProFormDateTimePicker } from './components/ProFormDateTimePicker.config';
import { configProFormDateRangePicker } from './components/ProFormDateRangePicker.config';
import { configProFormDateTimeRangePicker } from './components/ProFormDateTimeRangePicker.config';
import { configProFormTextPassword } from './components/ProFormText.Password.config';
import { configProFormTimePicker } from './components/ProFormTimePicker.config';
import { configProFormTextArea } from './components/ProFormTextArea.config';

Builder.registerComponent(withChildren(ProForm), configProForm);
Builder.registerComponent(ProFormText, configProFormText);
Builder.registerComponent(ProFormText.Password, configProFormTextPassword);
Builder.registerComponent(ProFormTextArea, configProFormTextArea);
Builder.registerComponent(ProFormDatePicker, configProFormDatePicker);
Builder.registerComponent(ProFormTimePicker, configProFormTimePicker);
Builder.registerComponent(ProFormDateTimePicker, configProFormDateTimePicker);
Builder.registerComponent(ProFormDateRangePicker, configProFormDateRangePicker);
Builder.registerComponent(ProFormDateTimeRangePicker, configProFormDateTimeRangePicker);
Builder.registerComponent(withChildren(ProTable), configProTable);